version: 2

defaults: &defaults
  docker:
    - image: gaozhi/mysql-client-alpine
    - image: circleci/mysql:5.6

jobs:
  one:
    <<: *defaults
    steps:
      - run:
          name: Greeting
          command: sleep 10
      - run:
          name: Greeting
          command: |
            mysql -u root -h 127.0.0.1  -e 'show databases;'
  two:
    <<: *defaults
    steps:
      - run:
          name: Greeting
          command: echo TWO

workflows:
  version: 2
  test:
    jobs:
      - one
      - two
